### ISSUE TITLE
Doesn't work with dates

### ISSUE THREAD

**Issue by gordon-matt** [xiadevisser/query-builder-odata#6]
I am trying to query by a date range, as follows:

```
if (dateLogFrom) {
    query.filter(f => f.ge('DateLog', dateLogFrom));
}

if (dateLogTo) {
    query.filter(f => f.le('DateLog', dateLogTo));
}
```

This does not work, because the resulting filter places single quotes around the dates:

`?$filter=DateLog ge '2022-02-01' and DateLog le '2022-02-03'`

I then also tried to see what would happen if I passed in a JavaScript date object instead:

```
if (dateLogFrom) {
    query.filter(f => f.ge('DateLog', Date.parse(dateLogFrom)));
}

if (dateLogTo) {
    query.filter(f => f.le('DateLog', Date.parse(dateLogTo)));
}
```

That results in the following:

`?$filter=DateLog ge 1643673600000 and DateLog le 1643846400000`

No quotes this time, but obviously OData doesn't understand that at all..

The filter builder needs to either detect Date objects and write them out in the format OData expects.. example:

`?$filter=DateLog ge 2022-02-01T00:00:00.00Z and DateLog le 2022-02-03T00:00:00.00Z`

or perhaps have some way of detecting that the string passed in is a date and just not enquote it..

**Comment by gordon-matt** [comment]
Any update on this? I noticed the same issue for GUIDs as well. I get an error like this:

```
ODataException: A binary operator with incompatible types was detected. Found operand types 'Edm.Guid' and 'Edm.String' for operator kind 'Equal'.
```

This is because a GUID should not be wrapped in quotes like a string. In order to solve the issue for both dates and GUIDs, I have a suggestion; could you add another parameter to the functions? Example for `eq`:

```
query.filter(f => f.eq('SupplierProfileId', supplierProfileId, 'guid'));
```
If the 3rd arg is not present, then the default behavior of `string` should be applied (wrap in quotes). If the 3rd arg is `guid`, then don't wrap in quotes... and for datetime, we could have this:

```
query.filter(f => f.ge('DateLog', dateLogFrom, 'datetime'));
```

And that would then parse the value as a date and format the result the way that OData expects.

Thoughts?

**Comment by xiadevisser** [comment]
Thanks for the suggestion! Hopefully this solves your problem.

**Comment by gordon-matt** [comment]
It's working great, thanks!
